import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Header } from '../layout/Header'
import { Footer } from '../layout/Footer'
import Layout from '../layout/Layout'
import Login from "../pages/login"
import  HomeData  from './homeData'
import {Announcements} from "./announcements"
import Register from './register'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
export default function Home({children}) {
    const router = useRouter()
    useEffect(() => {
      console.log(router.query)
      });
  return (
    <div className={styles.container}>
      <Head>
        <title>My school app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
     </Head>

     <HomeData/>
     
      
    </div>
  )
}

/*

export async function getStaticProps() {
  const product_res = await fetch(`${API_URL}/products/`)
  const products = await product_res.json()

  return {
    props: {
        products
    }
  }
}

*/
